ecom_dbt:
  outputs:
    dev:
      account: hc45570.eu-central-1
      database: ECOM_DB
      password: Tm@300820030906
      role: dbt_role
      schema: ECOM_SCHEMA
      threads: 10
      type: snowflake
      user: maisnowy3008
      warehouse: E_COMMERCE
  target: dev
